import "../src/components/text";
import "../src/components/button";
import "../src/components/back-button";
import "../src/components/rock";
import "../src/components/paper";
import "../src/components/scissors";
// import "../../../mod4/desafio-final/src/components/rock";
// import "../../../mod4/desafio-final/src/components/paper";
// import "../../../mod4/desafio-final/src/components/scissors";
import "./components/result";
import "./components/score";
import "../src/components/label";
import "../src/components/input";
import "./pages/home";
import "./pages/signup";
import "./pages/login";
import "./pages/lobby";
import "./pages/seek-room";
import "./pages/room";
import "./pages/instruccions";
import "./pages/in-game";
import "./pages/picks";
import "./pages/result";
import "./pages/probando";
import "./router";
